name: Publish to AUR

on:
  push:
    branches:
      - main

jobs:
  aur-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Publish yamp-git to AUR
        uses: KSXGitHub/github-actions-deploy-aur@master
        with:
          pkgname: yamp-git
          pkgbuild: ./PKGBUILD 
          commit_username: ${{ github.actor }}
          commit_email: ${{ github.actor }}@users.noreply.github.com
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Automated update via GitHub Actions"
          force_push: true
